apiVersion: apps/v1
kind: Deployment
metadata:
  name: audion-app
  labels:
    app: audion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audion-app
  template:
    metadata:
      labels:
        app: audion-app
    spec:
      containers:
      - name: audion-app
        image: YOUR_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/audion-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: database-url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: database-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: jwt-secret
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: aws-access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: aws-secret-key
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: s3-bucket
        - name: AI_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: ai-server-url
        - name: XAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: audion-secrets
              key: xauth-secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: audion-app-service
spec:
  selector:
    app: audion-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer