spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/audion_db}
    username: ${DATABASE_USERNAME:audion_user}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:}
  exp-hours: ${JWT_EXP_HOURS:12}
  issuer: ${JWT_ISSUER:AudIon}
  kid: ${JWT_KID:v1}


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    s3:
      bucket: ${AWS_S3_BUCKET:}
    region:
      static: ${AWS_REGION:ap-northeast-2}

ai:
  server:
    url: ${AI_SERVER_URL:http://ai-server:8081}
xauth:
  secret: ${XAUTH_SECRET:}
