spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audion_db
    username: audion_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    credentials:
      access-key: <AWS_ACCESS_KEY>
      secret-key: <AWS_SECRET_KEY>
    s3:
      bucket: <YOUR_BUCKET_NAME>
    region:
      static: ap-northeast-2

ai:
  server:
    url: http://ai-server:5000
