spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audion_db
    username: audion_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false # 개발에서는 Flyway 끔

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 자동 반영
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: o1qk7t9vY7g1Rr7qkq0wV9y2t1A2L7v8t6h2C0l5r9Qy2w6x8s4m3p0n5u7a9c1   # 환경변수로 주입 권장
    exp-hours: 12
    issuer: AudIon
    kid: v1
